"""add PDF processing fields to papers

Revision ID: 768976a24483
Revises: 96f9b19a327f
Create Date: 2026-07-26 11:23:56.841837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "768976a24483"
down_revision: str | Sequence[str] | None = "96f9b19a327f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("papers", sa.Column("raw_text", sa.Text(), nullable=True))
    op.add_column("papers", sa.Column("sections", sa.JSON(), nullable=True))
    op.add_column("papers", sa.Column("references", sa.JSON(), nullable=True))
    op.add_column("papers", sa.Column("parser_used", sa.String(length=50), nullable=True))
    op.add_column("papers", sa.Column("parser_metadata", sa.JSON(), nullable=True))
    op.add_column("papers", sa.Column("pdf_processed", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("papers", sa.Column("pdf_processing_date", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "papers", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("papers", "updated_at")
    op.drop_column("papers", "pdf_processing_date")
    op.drop_column("papers", "pdf_processed")
    op.drop_column("papers", "parser_metadata")
    op.drop_column("papers", "parser_used")
    op.drop_column("papers", "references")
    op.drop_column("papers", "sections")
    op.drop_column("papers", "raw_text")
    # ### end Alembic commands ###
